name: stripe_payment_flutter
description: A Flutter plugin to integrate the stripe libraries for iOS and Android. Supports Apple / Google Pay, SCA, PSD2 and much more. An alternative version for developers that have conflict with react native package
version: 1.1.1
homepage: https://github.com/luuduchieu/stripe_payment_flutter
authors:
- Jonas Bark <jonas.bark@gmx.de>
- John Blanchard <jnblanchard@mac.com>
- Harry Luu <luuduchieuharry@gmail.com>

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: de.jonasbark.stripepayment
        pluginClass: StripePaymentPlugin
      ios:
        pluginClass: StripePaymentPlugin
